### ISSUE TITLE
docker-compose not working (hashtag1281)

### ISSUE THREAD

**Issue by NobleMathews** [Mayil-AI-Sandbox/klaw-f3g23#34]
Hi, 

i am using docker desktop in windows 10.

this is my docker compose file ,  and this is the exception when i try to Test the conection to Cluster Api URL ( Dashboard -> settings )

klaw-klaw-core-1         | org.springframework.web.client.ResourceAccessException: I/O error on GET request for " Connection refused
klaw-klaw-core-1         |      at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[spring-web-6.0.8.jar!/:6.0.8]
klaw-klaw-core-1         |      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[spring-web-6.0.8.jar!/:6.0.8]
klaw-klaw-core-1         |      at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar!/:6.0.8]
klaw-klaw-core-1         |      at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646) ~[spring-web-6.0.8.jar!/:6.0.8]
klaw-klaw-core-1         |      at io.aiven.klaw.service.ClusterApiService.getClusterApiStatus(ClusterApiService.java:162) ~[classes!/:2.3.0]
klaw-klaw-core-1         |      at io.aiven.klaw.service.ServerConfigService.testClusterApiConnection(ServerConfigService.java:568) ~[classes!/:2.3.0]
klaw-klaw-core-1         |      at io.aiven.klaw.controller.ServerConfigController.testClusterApiConnection(ServerConfigController.java:69) ~[classes!/:2.3.0]
klaw-klaw-core-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
klaw-klaw-core-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

---
version: '3'
services:
  klaw-core:
    image: aivenoy/klaw-core:latest
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: dGVzdHRlc3R0ZXN0MTIzYWRhZGFzZGFzZGF0ZXN0dGVzdHRlc3QxMjNhZGFkYXNkYXNkYXRlc3R0ZXN0dGVzdDEyM2FkYWRhc2Q=
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/klaw/klawprodb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"
    ports:
    -   "9097:9097"
    volumes:
      - "klaw_data:/klaw"
    extra_hosts:
      - "moby:127.0.0.1"
  
  klaw-cluster-api:
    image: aivenoy/klaw-cluster-api:latest
    hostname: localhost
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: dGVzdHRlc3R0ZXN0MTIzYWRhZGFzZGFzZGF0ZXN0dGVzdHRlc3QxMjNhZGFkYXNkYXNkYXRlc3R0ZXN0dGVzdDEyM2FkYWRhc2Q=
    ports:
    -   "9343:9343" 
    volumes:
      - "klaw_data:/klaw"
    extra_hosts:
      - "moby:127.0.0.1"
volumes:
  klaw_data:
    driver: local

The cluster api is the same, could you help me?

Regards, 
Leonardo

**Comment by NobleMathews** [comment]
Hey  we have a docker compose file that might help you get started [here](

I think the big difference is that network_mode: "host" is used what this does is it runs the image using the local machines network. (Also be aware if you copy the above template that you just need to update it to point to the release image or else build it locally.) I am currently working on updating this documentation for the docker install at the moment to hopefully make it easier to get started. 

Documentation here


What is currently happening i think is that the two docker images are unable to communicate between docker containers.
If you are happy to add the network_mode config I think that will get you up and running pretty fast.
If there is an issue with using host then I think you will need to setup a bridge network 

The rest of your setup looks good though so hopefully this is a quick fix!

**Comment by NobleMathews** [comment]
thanks

**Comment by NobleMathews** [comment]
Sorry for the delay we have updated the documentation for the deployment of klaw via docker and tested, Ubuntu, Mac and Windows deployments.
